# *Numpy(Part_01)*

In [3]:
# import libraries
import numpy as np

In [7]:
a = np.arange(6)
print(a)
a.ndim

[0 1 2 3 4 5]


1

In [8]:
a2 = a[np.newaxis, ::1] # add new axis at row position 0 (row 0)  

print(a2)
a2.ndim

[[0 1 2 3 4 5]]


2

In [9]:
a3 = a[np.newaxis, :, np.newaxis]  # row 0, column 2
print(a3)
print(a3.shape)
print(a3.ndim)  # 3

[[[0]
  [1]
  [2]
  [3]
  [4]
  [5]]]
(1, 6, 1)
3


In [10]:
import numpy as np
a = np.array([1,2,3])
print("Original a:", a, a.shape, a.ndim)  # (3,), 1D

# Add 2 new axes → 3D
a3 = a[np.newaxis, :, np.newaxis]
print(a3)
print("Shape:", a3.shape)  # (1, 3, 1)
print("Dimensions:", a3.ndim)  # 3

Original a: [1 2 3] (3,) 1
[[[1]
  [2]
  [3]]]
Shape: (1, 3, 1)
Dimensions: 3


In [12]:
a =np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [11]:
# If you to check length of array
len(a)

3

In [13]:
# I f you find dimension of this array
a.ndim

1

In [15]:
z = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
z.shape

(3, 4)

In [19]:
print(z[0:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
z.ndim

2

In [21]:
# If you want to create 0 array
t=np.zeros(5)
print(t)
# If you want to create 1 array
z=np.ones(5)
print(z)

z = np.full(5, 3)
print(z)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[3 3 3 3 3]


$Layer 0:       Layer 1:
[ [1,2],       [ [9,10],
  [3,4] ]        [11,12] ]$

# What is array?

-  In computer programming, an array is a data structure that stores a collection of elements, each identified by an index or a key. Arrays are used to store a fixed-size sequential collection of elements of the same type, such as integers or strings. 

In Python, arrays are implemented as lists. A list is a collection of values that can be of different types, including other lists. Lists are mutable, which means that their contents can be modified after they are created. 

Numpy is a Python library that provides support for arrays and matrices. Numpy arrays are similar to lists, but they are more efficient for numerical operations and can be multi-dimensional. Numpy arrays are homogeneous, which means that all elements in the array must be of the same type. Numpy arrays are also immutable, which means that their size and contents cannot be changed after they are created.

# Assignment Day 28

# *Why do we have 1D, 2D or 3D arrays?*
•    1D arrays are useful for representing data that has a single dimension, such as a list of numbers or a                  sequence of characters. For example, you might use a 1D array to store the temperature readings for a            day, or the names of students in a class.

•    2D arrays are useful for representing data that has two dimensions, such as an image or a table. For                 example, you might use a 2D array to store the pixel values of an image, or the data in a spreadsheet.

•    3D arrays are useful for representing data that has three dimensions, such as a video or a medical                    image. For example, you might use a 3D array to store the video frames of a video, or the voxels of a                 medical image.

# Where we need them in Data Science?
•    1D arrays:
o    Storing the results of a scientific experiment
o    Representing the features of a data point in machine learning
o    Encoding text data for natural language processing

•    2D arrays:
o    Storing the image data for a machine learning model
o    Representing a matrix of numbers for linear algebra operations
o    Creating a heatmap or other data visualization

•    3D arrays:
o    Storing the data for a video or medical image
o    Representing a 3D model for computer vision tasks
o    Simulating the flow of fluids in computational fluid dynamics