In [60]:
import numpy as np

In [65]:
# Create an empty array with 2 elements
np.empty(1) 

array([1.40174625e-311])

In [66]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [67]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [6]:
np.linspace(0, 10, num=5) # Is ka mtlb 0 se 10 tak 5 numbers

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [68]:
np.linspace(2, 10, num=6)

array([ 2. ,  3.6,  5.2,  6.8,  8.4, 10. ])

In [69]:
x = np.ones(3, dtype=np.int64)
x

array([1, 1, 1], dtype=int64)

In [70]:
x = np.zeros(2, dtype=np.int64)
x

array([0, 0], dtype=int64)

# Adding, removing, and sorting elements

In [71]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr.sort()
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [72]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [73]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [74]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

In [82]:
a = np.concatenate((x, y), axis=1)
print(a)
#print length of a
print(len(a))
a.ndim

[[1 2 5 6]
 [3 4 7 8]]
2


2

# How do you know the shape and size of an array?

In [ ]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example.ndim

3

In [15]:
array_example.shape

(3, 2, 4)

In [4]:
array_example.size

24

In [90]:
a = np.arange(8)
print(a)

[0 1 2 3 4 5 6 7]


In [91]:
print(a)
print(a.shape)
print(a.ndim)

[0 1 2 3 4 5 6 7]
(8,)
1


In [94]:
b = a.reshape(1,1, 8)
print(b)

print(b.shape)
print(b.size)
print(b.ndim)

[[[0 1 2 3 4 5 6 7]]]
(1, 1, 8)
8
3


In [98]:
np.reshape(a, newshape=(1, 8), order='C')

array([[0, 1, 2, 3, 4, 5, 6, 7]])

In [20]:
np.ndim

<function ndim at 0x00000255A770F930>

# How to convert a 1D array into a 2D array (how to add a new axis to an array)

In [102]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
a.shape

[1 2 3 4 5 6]


(6,)

In [ ]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [23]:
row_vector = a[: ,np.newaxis]
row_vector.shape

(6, 1)

In [104]:
z = np.array([1, 2, 3, 4, 5, 6])
z.shape

(6,)

In [109]:
b = np.expand_dims(z, axis=1)
b.shape

(6, 1)

# Indexing & Slicing

In [110]:
data = np.array([1, 2, 3,4,5])

In [113]:
data[:-2
     ]

array([1, 2, 3])

In [114]:
y = np.array([[1 , 2, 3, 4],
               [5, 6, 7, 8], 
               [9, 10, 11, 12]])

In [115]:
len(y)

3

In [16]:
y.shape

(3, 4)

In [17]:
y.size

12

In [18]:
y.ndim

2

In [120]:
b = np.array([1, 2, 3,4,5,6,7])

In [117]:
print(b[b < 5])

[1 2 3 4]


In [122]:
five_up = (b <= 5)
print(b[five_up])

[1 2 3 4 5]


In [123]:
divisible_by_2 = b[b%3==0]
print(divisible_by_2)

[3 6]


In [124]:
c = b[(b > 2) & (b < 11)]
print(c)

[3 4 5 6 7]


In [125]:
u = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [126]:
a = np.array([1, 2, 3, 4, 5, 6,13,15,45,34,32])

In [128]:
b = np.nonzero(a < 5)
print(b)

(array([0, 1, 2, 3], dtype=int64),)


In [130]:
not_there = np.nonzero(a == 6)
print(not_there)


(array([5], dtype=int64),)


In [46]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [131]:
a1 = np.array([[1, 1],
               [2, 2]])
a2 = np.array([[3, 3],
               [4, 4]])

In [132]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [54]:
x = np.arange(1, 25) .reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [133]:
x = np.arange(1, 31) .reshape(5, 6)
x

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [136]:
np.vsplit(y, 3)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

In [62]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [58]:
arr2d = np.array([[1,2,3],[4,5,6]])
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [139]:
b = arr + 5          # add scalar
c = arr * 2          # multiply scalar

print(b)
print(c)

[ 6  7  8  9 10 11 12 13]
[ 2  4  6  8 10 12 14 16]


In [138]:
arr2d + arr2d 

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [140]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [149]:
b1 = a[-1, :]
b1

array([ 9, 10, 11, 12])

In [153]:
b = np.array([1, 2, 3, 4, 5])

In [154]:
b[0] = 99
b

array([99,  2,  3,  4,  5])

In [67]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [156]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)

print(data)
print(ones)
print(data + ones)

[1 2]
[1 1]
[2 3]


In [157]:
data * data

array([1, 4])